language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pmazanik/docker-react -f Dockerfile.dev . 
  
script:
  - docker run -e CI=true pmazanik/docker-react npm run test
